language: csharp
solution: CIRelay.sln

mono: none
dotnet: 2.1.403

install:
    - dotnet restore

script:
    - dotnet build

deploy:
  provider: azure_web_apps
  username: $azure_id       # If AZURE_WA_USERNAME isn't set
  password: $azure_pwd   # If AZURE_WA_PASSWORD isn't set
  site: https://cirelay20181102082324.azurewebsites.net       # If AZURE_WA_SITE isn't set
