language: csharp
solution: CIRelay.sln

mono: none
dotnet: 2.1.403

install:
    - dotnet restore

script:
    - dotnet build

deploy:
  provider: azure_web_apps
  site: https://cirelay20181102082324.azurewebsites.net       # If AZURE_WA_SITE isn't set
